#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nSuper user right are needed $0"
	exit 1;
fi

echo "Install dependencies"
pip3 install paho-mqtt pynng

echo "Copy needed files"
if [ ! -d "/opt/gardenalocalcontrol/" ];then
	mkdir /opt/gardenalocalcontrol/
	chown -R $USER /opt/gardenalocalcontrol/
	chmod -R 0755 /opt/gardenalocalcontrol/
fi

cp gardenalocalcontrol.py /opt/gardenalocalcontrol

python3 /opt/gardenalocalcontrol/gardenalocalcontrol.py
