#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nSuper user right are needed $0"
	exit 1;
fi

echo "Install dependencies"
pip3 install paho-mqtt
pip install paho-mqtt
echo "Copy needed files"
if [ ! -d "/opt/gardenalocalcontrol/" ];then
	mkdir /opt/gardenalocalcontrol/
	chown -R $USER /opt/gardenalocalcontrol/
	chmod -R 0755 /opt/gardenalocalcontrol/
fi

cp gardenalocalcontrol.py /opt/gardenalocalcontrol

cp gardenalocalcontrol.service /etc/systemd/system
chmod a+x /etc/systemd/system/gardenalocalcontrol.service
systemctl --system daemon-reload
systemctl start gardenalocalcontrol.service